public class Movie {
   public static String descendingOrder(/*the brackets will need to be filled with the data type from movieDatabase.java*/) {
       String list = "example";
       return list;
   }
   public static String lowestRated(){
       String lowestMovie = "Sharknado";
       return lowestMovie;
   }

   public static String fifthPGfilm(){
       String fifthFilm = "Shrek";
       return fifthFilm;
   }

   public static String longestMovieName(){
       String longestName = "Die Hard";
       return longestName;
   }

   public static Integer filmYearDifference(){
       Integer yearGap = 12;
       return yearGap;
   }
}
